# -*- coding: utf-8 -*-
"""Fnn.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IrepvLpHeNU_FsCs8h2JyM7K47GYXG6h
"""

import pandas as pd

file_path = "/content/sample_data/iec104_treated_balanced.csv"
df = pd.read_csv(file_path)

print(df.shape)
print(df.head())

# Commented out IPython magic to ensure Python compatibility.
!git clone https://github.com/j99tang/ECE1513.git

# %cd ECE1513/SVM/data/

import pandas as pd
import glob
import os

path = os.getcwd()
csv_files = glob.glob(os.path.join(path, "*.csv"))

print(f"find {len(csv_files)} file:")
for f in csv_files:
    print("-", os.path.basename(f))

li = []
for filename in csv_files:
    df = pd.read_csv(filename, index_col=None, header=0)
    li.append(df)
combined_df = pd.concat(li, axis=0, ignore_index=True)
print("\n conbin finish！")
print(f"Total: {len(combined_df)}")
combined_df.head()

combined_df.head()

print(df.columns.tolist())

print(df.shape)

from sklearn.preprocessing import StandardScaler, LabelEncoder
from torch.utils.data import TensorDataset, DataLoader
import torch

def prepare_dataloaders(train_df, val_df, label_col='Label', batch_size=128):

    X_train = train_df.drop(columns=[label_col])
    y_train = train_df[label_col]

    X_val = val_df.drop(columns=[label_col])
    y_val = val_df[label_col]

    #2. Label Encoding
    le = LabelEncoder()
    y_train = le.fit_transform(y_train)
    y_val = le.transform(y_val)

    scaler = StandardScaler()
    X_train = scaler.fit_transform(X_train)
    X_val = scaler.transform(X_val)

    X_train = torch.tensor(X_train, dtype=torch.float32)
    y_train = torch.tensor(y_train, dtype=torch.long)

    X_val = torch.tensor(X_val, dtype=torch.float32)
    y_val = torch.tensor(y_val, dtype=torch.long)

    train_loader = DataLoader(
        TensorDataset(X_train, y_train),
        batch_size=batch_size,
        shuffle=True
    )

    val_loader = DataLoader(
        TensorDataset(X_val, y_val),
        batch_size=batch_size,
        shuffle=False
    )

    return train_loader, val_loader, X_train.shape[1], len(le.classes_)

import torch.nn as nn

class FNN(nn.Module):
    def __init__(self, input_dim, num_classes):
        super(FNN, self).__init__()

        self.model = nn.Sequential(
            nn.Linear(input_dim, 256),
            nn.ReLU(),
            nn.BatchNorm1d(256),
            nn.Dropout(0.3),

            nn.Linear(256, 128),
            nn.ReLU(),
            nn.BatchNorm1d(128),
            nn.Dropout(0.3),

            nn.Linear(128, 64),
            nn.ReLU(),

            nn.Linear(64, num_classes)
        )

    def forward(self, x):
        return self.model(x)

def train_model(model, train_loader, val_loader, optimizer, criterion, device, epochs=30):

    model.to(device)

    train_losses = []
    val_losses = []
    val_accuracies = []

    for epoch in range(epochs):

        #TRAIN
        model.train()
        total_loss = 0

        for X, y in train_loader:
            X, y = X.to(device), y.to(device)

            optimizer.zero_grad()
            outputs = model(X)

            loss = criterion(outputs, y)
            loss.backward()
            optimizer.step()

            total_loss += loss.item()

        avg_train_loss = total_loss / len(train_loader)
        train_losses.append(avg_train_loss)

        #VALID
        model.eval()
        val_loss = 0
        correct = 0
        total = 0

        with torch.no_grad():
            for X, y in val_loader:
                X, y = X.to(device), y.to(device)

                outputs = model(X)
                loss = criterion(outputs, y)

                val_loss += loss.item()

                _, preds = torch.max(outputs, 1)
                total += y.size(0)
                correct += (preds == y).sum().item()

        avg_val_loss = val_loss / len(val_loader)
        val_acc = correct / total

        val_losses.append(avg_val_loss)
        val_accuracies.append(val_acc)

        print(f"Epoch {epoch+1} | "
              f"Train Loss: {avg_train_loss:.4f} | "
              f"Val Loss: {avg_val_loss:.4f} | "
              f"Val Acc: {val_acc:.4f}")

    return model, train_losses, val_losses, val_accuracies

label = combined_df["Label"]
features = combined_df.drop(columns=["Label"])
features = features.drop(
    columns=[
        "Flow ID", "Src IP", "Dst IP", "Timestamp",
        "Src Port", "Dst Port", "Protocol"
    ],
    errors="ignore"
)

features = features.apply(pd.to_numeric, errors='coerce')

features = features.fillna(0)

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
label = le.fit_transform(label)

combined_df = features
combined_df["Label"] = label

print(combined_df["Label"].value_counts())

from sklearn.model_selection import train_test_split
#use raw da'ta
train_df, val_df = train_test_split(
    combined_df,
    test_size=0.2,
    stratify=combined_df['Label'],
    random_state=42
)

max_per_class = 3000

balanced_data = []

for label_value, group in train_df.groupby("Label"):
    if len(group) > max_per_class:
        sampled = group.sample(max_per_class, random_state=42)
    else:
        sampled = group

    balanced_data.append(sampled)

train_df = pd.concat(balanced_data).sample(frac=1, random_state=42).reset_index(drop=True)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

train_loader, val_loader, input_dim, num_classes = prepare_dataloaders(train_df, val_df)

model = FNN(input_dim, num_classes)

optimizer = torch.optim.Adam(model.parameters(), lr=1e-3)

from sklearn.utils.class_weight import compute_class_weight
import numpy as np

classes = np.unique(train_df['Label'])

class_weights = compute_class_weight(
    class_weight='balanced',
    classes=classes,
    y=train_df['Label']
)
weights = torch.zeros(num_classes)

for i, c in enumerate(classes):
    weights[int(c)] = class_weights[i]

weights = weights.to(device)

criterion = nn.CrossEntropyLoss(weight=weights)
model, train_losses, val_losses, val_accs = train_model(
    model,
    train_loader,
    val_loader,
    optimizer,
    criterion,
    device,
    epochs=20
)

#use balanced data
from sklearn.model_selection import train_test_split

train_df, val_df = train_test_split(
    df,
    test_size=0.2,
    stratify=df['Label'],
    random_state=42
)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

train_loader, val_loader, input_dim, num_classes = prepare_dataloaders(train_df, val_df)

model = FNN(input_dim, num_classes)

optimizer = torch.optim.Adam(model.parameters(), lr=1e-3)
criterion = nn.CrossEntropyLoss()

model, train_losses, val_losses, val_accs = train_model(
    model,
    train_loader,
    val_loader,
    optimizer,
    criterion,
    device,
    epochs=20
)

from sklearn.metrics import classification_report

def evaluate(model, val_loader, device):
    model.eval()

    all_preds = []
    all_labels = []

    with torch.no_grad():
        for X, y in val_loader:
            X = X.to(device)

            outputs = model(X)
            _, preds = torch.max(outputs, 1)

            all_preds.extend(preds.cpu().numpy())
            all_labels.extend(y.numpy())

    print(classification_report(all_labels, all_preds))

evaluate(model, val_loader, device)

import matplotlib.pyplot as plt

def plot_loss(train_losses, val_losses=None):
    plt.figure(figsize=(6,4))
    plt.plot(train_losses, label='Train Loss')

    if val_losses:
        plt.plot(val_losses, label='Validation Loss')

    plt.xlabel("Epoch")
    plt.ylabel("Loss")
    plt.title("Training Loss Curve")
    plt.legend()
    plt.show()

plot_loss(train_losses, val_losses)